### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tempest-kitty** [iionly/elggx_userpoints#2]
I'm not sure if you take feature requests or not but I thought I might just make a small suggestion.

Is it possible to be able to assign a user or select users to be able to add and deduct points without having to set them as a site admin? 

Also adding the functionality of only allowing access to certain groups based on a users userpoints. 

Thanks for your time and great work on this plugin!

**Comment by iionly** [comment]
I'm interested in feature request. It's just that I might not have the time to implement such features on short term.

Some remarks regarding your two suggestions...

Giving non-admins the possibility to add/substract userpoints from other users is surely possible to implement. But I doubt that many admins would need such a feature. Additionally, the question is how to handle the specific permission that is necessary for a normal user being able to modify the userpoints of other users. The questions is if such a permissions would be just one of a number of special features that such users should have (i.e. kind of moderator users). In this case it would be more appropriate to deal with the managing of userpoints of other users in the greater context of implementing / introducing some specific type of user (in other words introducing some speific role for users). There's a roles plugin available that handles the management of such roles. Of course, there would be some specific code necessary for a user having the appropriate role being able to add/substract userpoints. But this would possible be a smaller part of the task of implementing such a moderator type of users - even more so as the roles framework and its associated plugins are not yet user-friendly enough to be used out-of-the-box with all kind of 3rd party plugins. It's mote a matter of developing a specific customization plugin for every single Elgg site that takes into account the specific requirements the site admins has in mind for this site.

Limiting the possibility of joining groups based on the number of userpoints is surely also a possibility. But it's not as simple as it might seem at first. You also need to consider that users could lose points and might fall below the limit necessary to be able to join a group. If they already became a member, should they lose their membership again? Possibly not. But you have to keep a record of them being allowed to stay members then independently of their current number of points (in the Elggx Badges plugin there's a similar functionality already implemented but that's only for a single badge and not for a possible unlimited number of groups necessary to be handled). Also, users can be invited by other users to join a group. With a userpoints limit the invitation process would have to be modified to prevent users from inviting other users who not have the necessary number of points. Otherwise, it would surely be confusing and quite likely also annoying (you get an invitation but then you can't joint the group nevertheless). If I have the time to work on such a feature that handles group joining limitation based on userpoints I will most likely implement it as a separate plugin. The userpoints plugin itself is aiming more on the functionality of handling the management of userpoints as such and does not deal with specific additional features that are building up on the userpoints.

As I mentioned the main problem I (always) have is the lack of time necessary to work on implementing any features suggested. I will surely keep your suggestions in mind and if I have the time I'll give it a try. But I can't give you any estimation when this might be the case unfortunately. I'll keep this issue open for sure as a reminder.

**Comment by iionly** [comment]
Sorry. But I've decided to not make any changes or add more options for the foreseeable future. I've just too much to maintain already as it is.
